#!/usr/bin/env sh

########################################################################
# Streamlink helper script for TVHeadend pipe://
#
# Note: Keep it POSIX shell compliant for compatibility
#
# Author: cgomesu
# Repo: https://github.com/cgomesu/tvhlink
#
# Related docs:
# - Streamlink: https://streamlink.github.io/cli.html#command-line-usage
########################################################################


usage () {
  echo ''
  echo 'Author: cgomesu'
  echo 'Repo: https://github.com/cgomesu/tvhlink'
  echo ''
  echo 'Usage:'
  echo ''
  echo "$0"' [OPTIONS] <URL> '
  echo ''
  echo '  URL:'
  echo '    One or more http(s) URLs. If multiple, use space to separate them. Order defines priority.'
  echo ''
  echo '  OPTIONS:'
  echo '    -h  Show this help message.'
  echo '    -q  Stream quality profile. It allows fallback profiles. For example:'
  echo '        -q "1080p,720p,best" tries 1080p first, then 720p, then whatever is the best.'
  echo '        The default is "best".'
  echo ''
}

if [ -z "$(command -v streamlink)" ]; then echo 'ERROR: streamlink executable not found'; exit 1; fi

while getopts 'hq:' OPT; do
  case $OPT in
    h) usage; exit 0;;
    q) QUALITY="$OPTARG"; if [ -z "$QUALITY" ]; then QUALITY="best"; fi;;
    \?) echo 'ERROR: Invalid option in the arguments.'; usage; exit 1;;
  esac
done

# loop one or more URLs provided as arg
for URL in "$@"; do
  # use pattern match to find URL
  if [ ! "$URL" = "${URL#http}" ]; then streamlink --stdout --default-stream "$QUALITY" --url "$URL"; fi
done

# EOF means no stream found; exit with error
exit 1
